version: '3'
services:
  poshdev:
    build: dev
    domainname: poshdev
    hostname: poshdev
    ports:
      - "8888:8888"
    networks:
      - posh
    volumes:
      - .:/src
    cap_add:
      - SYS_PTRACE
networks:
  posh:
    external: true