
# Do not edit this file directly, generate with:
#     $ python setup.py makefile
# requires bottle (pip install bottle)

CXX=g++
CXXFLAGS=-c -Wall -std=c++11 -I./external/citar/include -I./src/posh_core/ -Iutils -I./external/citar/src/corpus -I./external/citar/src/cwrap -I./external/citar/src/tagger/hmm -I./external/citar/src/tagger/wordhandler -Isrc/posh_core 

all: posh_cli

posh_cli: \
posh_cli.o \
BrownCorpusReader.o \
BrownCorpusReaderPrivate.o \
cwrap.o \
HMMTagger.o \
HMMTaggerPrivate.o \
LinearInterpolationSmoothing.o \
LinearInterpolationSmoothingPrivate.o \
Model.o \
ModelPrivate.o \
KnownWordHandler.o \
SuffixWordHandler.o \
WordSuffixTree.o \
posh.o \
train.o \

	$(CXX) \
posh_cli.o \
BrownCorpusReader.o \
BrownCorpusReaderPrivate.o \
cwrap.o \
HMMTagger.o \
HMMTaggerPrivate.o \
LinearInterpolationSmoothing.o \
LinearInterpolationSmoothingPrivate.o \
Model.o \
ModelPrivate.o \
KnownWordHandler.o \
SuffixWordHandler.o \
WordSuffixTree.o \
posh.o \
train.o \
 -o posh_cli

# -----------------

posh_cli.o: ./utils/posh_cli.cpp
	$(CXX) $(CXXFLAGS) ./utils/posh_cli.cpp

BrownCorpusReader.o: ./external/citar/src/corpus/BrownCorpusReader.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/corpus/BrownCorpusReader.cpp

BrownCorpusReaderPrivate.o: ./external/citar/src/corpus/BrownCorpusReaderPrivate.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/corpus/BrownCorpusReaderPrivate.cpp

cwrap.o: ./external/citar/src/cwrap/cwrap.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/cwrap/cwrap.cpp

HMMTagger.o: ./external/citar/src/tagger/hmm/HMMTagger.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/HMMTagger.cpp

HMMTaggerPrivate.o: ./external/citar/src/tagger/hmm/HMMTaggerPrivate.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/HMMTaggerPrivate.cpp

LinearInterpolationSmoothing.o: ./external/citar/src/tagger/hmm/LinearInterpolationSmoothing.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/LinearInterpolationSmoothing.cpp

LinearInterpolationSmoothingPrivate.o: ./external/citar/src/tagger/hmm/LinearInterpolationSmoothingPrivate.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/LinearInterpolationSmoothingPrivate.cpp

Model.o: ./external/citar/src/tagger/hmm/Model.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/Model.cpp

ModelPrivate.o: ./external/citar/src/tagger/hmm/ModelPrivate.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/hmm/ModelPrivate.cpp

KnownWordHandler.o: ./external/citar/src/tagger/wordhandler/KnownWordHandler.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/wordhandler/KnownWordHandler.cpp

SuffixWordHandler.o: ./external/citar/src/tagger/wordhandler/SuffixWordHandler.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/wordhandler/SuffixWordHandler.cpp

WordSuffixTree.o: ./external/citar/src/tagger/wordhandler/WordSuffixTree.cpp
	$(CXX) $(CXXFLAGS) ./external/citar/src/tagger/wordhandler/WordSuffixTree.cpp

posh.o: src/posh_core/posh.cpp
	$(CXX) $(CXXFLAGS) src/posh_core/posh.cpp

train.o: src/posh_core/train.cpp
	$(CXX) $(CXXFLAGS) src/posh_core/train.cpp

clean:
	rm *o push_cli
	rm ./external/citar/include/citar/config.hh

